package io.terminus.core.cityfile

import io.terminus.core.geo.GeoMath
import io.terminus.core.geo.LatLng
import io.terminus.core.transit.RouteLine
import io.terminus.core.transit.Station
import io.terminus.core.transit.TransitEdge
import io.terminus.core.transit.TransitMode
import kotlin.math.roundToInt

/**
 * Deterministic generator for the two bundled synthetic demo cities
 * (ARCHITECTURE.md §4). The same objects are checked in as `.city.json.gz` under
 * `core/src/test/resources/cities/` and `app/src/main/assets/cities/`; a unit test
 * asserts that this generator and the checked-in artifacts agree exactly.
 *
 * All coordinates are computed from a base point plus metric east/north offsets
 * (StrictMath only, rounded to 6 decimals) so regeneration is bit-identical on any
 * platform. Both cities are `isSynthetic = true` and display-named "(demo city)".
 */
object DemoCities {

    const val DEMOVILLE_ID = "demoville"
    const val PORT_SALTMARSH_ID = "port-saltmarsh"

    /** Walking-transfer speed/penalty, matching the GTFS import (ARCHITECTURE.md §3 step 4). */
    private const val WALK_SPEED_MPS = 1.2
    private const val TRANSFER_PENALTY_SEC = 60.0

    private const val ATTRIBUTION =
        "Synthetic demo network generated by TERMINUS. Not based on any real-world transit data."

    fun all(): List<CityFile> = listOf(demoville(), portSaltmarsh())

    // =====================================================================
    // Demoville Metro — mid-size grid city centered at (52.050, 5.080)
    // =====================================================================

    /**
     * ARCHITECTURE.md §4: Line A (Red, metro, 14 stations east–west, ~750 m spacing,
     * A05–A09 underground + zone 1), Line B (Blue, metro, 13 stations north–south,
     * crossing at Central Cross = A07 = B07), Line C (Green, tram, 12-station loop
     * through the southwest, sharing Old Market = A04 = C03 and Garden Bridge =
     * B10 = C09). 36 distinct stations, 3 shared interchanges, 4 termini (the loop
     * has none), metro hops 90–150 s, tram hops 120–180 s, 6 walking-transfer pairs.
     * Default start: Central Cross.
     */
    fun demoville(): CityFile {
        val base = LatLng(52.050, 5.080)

        val lineANames = listOf(
            "Westfield Depot", "Millbrook", "Saint Anne's", "Old Market", "Foundry Lane",
            "Cathedral West", "Central Cross", "King's Arcade", "Riverside", "Brickyard",
            "Elm Park", "Tanners Row", "Dockside", "Harbor East",
        )
        val lineBNames = listOf(
            "North Heath", "Aspen Grove", "University", "Granite Square", "Northgate",
            "Fountain Court", "Central Cross", "Union Yard", "Willow Creek", "Garden Bridge",
            "South Meadow", "Cinder Hill", "South Pier",
        )
        // Loop stations (C03 = Old Market and C09 = Garden Bridge are the shared ones).
        val lineCSpecs = listOf(
            Triple("DV-C01", "Birch Hollow", -3750.0 to 210.0),
            Triple("DV-C02", "Pottery Lane", -3000.0 to 230.0),
            Triple("DV-A04", "Old Market", -2250.0 to 0.0),
            Triple("DV-C04", "Weavers Green", -1620.0 to -180.0),
            Triple("DV-C05", "Lime Kiln", -1250.0 to -750.0),
            Triple("DV-C06", "Moor End", -850.0 to -1300.0),
            Triple("DV-C07", "Heron Marsh", -550.0 to -1750.0),
            Triple("DV-C08", "Cooper's Field", -170.0 to -2450.0),
            Triple("DV-B10", "Garden Bridge", 0.0 to -1950.0),
            Triple("DV-C10", "Vine Street", -220.0 to -3230.0),
            Triple("DV-C11", "Saltworks", -1800.0 to -2700.0),
            Triple("DV-C12", "Westbrook Halt", -3050.0 to -230.0),
        )

        val routeA = "DV-LINE-A"
        val routeB = "DV-LINE-B"
        val routeC = "DV-LINE-C"

        val builder = CityBuilder(base)

        // Line A: east–west at the base latitude, 750 m spacing, A07 at the center.
        for (i in 1..14) {
            builder.station(
                id = "DV-A%02d".format(i),
                name = lineANames[i - 1],
                eastM = (i - 7) * 750.0,
                northM = 0.0,
                zoneId = if (i in 5..9) "1" else "2",
                underground = i in 5..9,
            )
        }
        // Line B: north–south at the base longitude, 650 m spacing, B07 = A07.
        for (i in 1..13) {
            if (i == 7) continue // Central Cross is DV-A07
            builder.station(
                id = "DV-B%02d".format(i),
                name = lineBNames[i - 1],
                eastM = 0.0,
                northM = (7 - i) * 650.0,
                zoneId = if (i in 5..9) "1" else "2",
                underground = false,
            )
        }
        // Line C loop: only the 10 non-shared stations are new.
        for ((id, name, offset) in lineCSpecs) {
            if (id.startsWith("DV-C")) {
                builder.station(
                    id = id,
                    name = name,
                    eastM = offset.first,
                    northM = offset.second,
                    zoneId = "2",
                    underground = false,
                )
            }
        }

        val lineAIds = (1..14).map { "DV-A%02d".format(it) }
        val lineBIds = (1..13).map { if (it == 7) "DV-A07" else "DV-B%02d".format(it) }
        val lineCIds = lineCSpecs.map { it.first }

        // Metro hops 90–150 s, tram hops 120–180 s; deterministic variety per hop index.
        builder.route(
            RouteLine(routeA, "A", "Demoville Line A (Red)", TransitMode.METRO, "#E03131", lineAIds),
            hopTimesSec = (1..13).map { 90 + 15 * ((it * 3) % 5) },
            closeLoop = false,
        )
        builder.route(
            RouteLine(routeB, "B", "Demoville Line B (Blue)", TransitMode.METRO, "#1971C2", lineBIds),
            hopTimesSec = (1..12).map { 90 + 15 * ((it * 2) % 5) },
            closeLoop = false,
        )
        builder.route(
            RouteLine(routeC, "C", "Demoville Line C (Green)", TransitMode.TRAM, "#2F9E44", lineCIds),
            hopTimesSec = (1..12).map { 120 + 15 * ((it * 3) % 5) },
            closeLoop = true,
        )

        // The 6 walking-transfer pairs (each emitted as two directed edges).
        builder.transfer("DV-A02", "DV-C01")
        builder.transfer("DV-A03", "DV-C02")
        builder.transfer("DV-A03", "DV-C12")
        builder.transfer("DV-A05", "DV-C04")
        builder.transfer("DV-B11", "DV-C08")
        builder.transfer("DV-B12", "DV-C10")

        return builder.build(
            cityId = DEMOVILLE_ID,
            displayName = "Demoville Metro (demo city)",
            defaultStartStationId = "DV-A07",
        )
    }

    // =====================================================================
    // Port Saltmarsh — small coastal town centered at (54.300, -1.500)
    // =====================================================================

    /**
     * ARCHITECTURE.md §4: Line 1 (Orange, tram) — 12 coast stations S01 Lighthouse
     * Point … S12 Salt Quay; Line 2 (Purple, bus) — inland loop interchanging at
     * S04 Town Hall and S09 Fish Market; Ferry F (Teal) — S12 → F01 Mid Anchorage →
     * F02 East Sands with 6-minute crossings. 26 distinct stations, zones 1/2, no
     * underground. Default start: Town Hall.
     */
    fun portSaltmarsh(): CityFile {
        val base = LatLng(54.300, -1.500)
        val builder = CityBuilder(base)

        val coastNames = listOf(
            "Lighthouse Point", "Gull Cliff", "Promenade", "Town Hall", "Old Pier",
            "Marine Gardens", "Bathing Huts", "Net Loft", "Fish Market", "Cooperage",
            "Brine Baths", "Salt Quay",
        )
        // Coast runs on a straight NW→SE diagonal, ~605 m between stations.
        for (i in 1..12) {
            builder.station(
                id = "PS-S%02d".format(i),
                name = coastNames[i - 1],
                eastM = -3000.0 + 435.0 * (i - 1),
                northM = 2200.0 - 420.0 * (i - 1),
                zoneId = if (i in 3..9) "1" else "2",
                underground = false,
            )
        }

        val inlandSpecs = listOf(
            Triple("PS-P01", "Windmill Rise", -2400.0 to 600.0),
            Triple("PS-P02", "Heather Down", -2700.0 to -100.0),
            Triple("PS-P03", "Shepherd's Gate", -2500.0 to -800.0),
            Triple("PS-P04", "Brackenfield", -1900.0 to -1300.0),
            Triple("PS-P05", "Marsh Lane", -1200.0 to -1600.0),
            Triple("PS-P06", "Tide Mill", -400.0 to -1700.0),
            Triple("PS-P07", "Cannery Row", 300.0 to -500.0),
            Triple("PS-P08", "High Street", -100.0 to 100.0),
            Triple("PS-P09", "Saint Olaf's", -500.0 to 700.0),
            Triple("PS-P10", "Orchard End", -900.0 to 1300.0),
            Triple("PS-P11", "Beacon Hill", -1500.0 to 1700.0),
            Triple("PS-P12", "Drovers Way", -1900.0 to 1400.0),
        )
        for ((id, name, offset) in inlandSpecs) {
            builder.station(
                id = id,
                name = name,
                eastM = offset.first,
                northM = offset.second,
                zoneId = if (id.removePrefix("PS-P").toInt() >= 7) "1" else "2",
                underground = false,
            )
        }

        builder.station("PS-F01", "Mid Anchorage", 2600.0, -1900.0, zoneId = "2", underground = false)
        builder.station("PS-F02", "East Sands", 3300.0, -1300.0, zoneId = "2", underground = false)

        val coastIds = (1..12).map { "PS-S%02d".format(it) }
        val loopIds = listOf("PS-S04") +
            (1..6).map { "PS-P%02d".format(it) } +
            listOf("PS-S09") +
            (7..12).map { "PS-P%02d".format(it) }

        builder.route(
            RouteLine("PS-LINE-1", "1", "Coast Line (Orange)", TransitMode.TRAM, "#F08C00", coastIds),
            hopTimesSec = (1..11).map { 120 + 15 * ((it * 3) % 5) },
            closeLoop = false,
        )
        builder.route(
            RouteLine("PS-LINE-2", "2", "Inland Loop (Purple)", TransitMode.BUS, "#9C36B5", loopIds),
            hopTimesSec = (1..14).map { 120 + 15 * ((it * 2) % 5) },
            closeLoop = true,
        )
        builder.route(
            RouteLine(
                "PS-FERRY-F", "F", "Harbour Ferry (Teal)", TransitMode.FERRY, "#0CA678",
                listOf("PS-S12", "PS-F01", "PS-F02"),
            ),
            hopTimesSec = listOf(360, 360), // 6-minute crossings
            closeLoop = false,
        )

        return builder.build(
            cityId = PORT_SALTMARSH_ID,
            displayName = "Port Saltmarsh (demo city)",
            defaultStartStationId = "PS-S04",
        )
    }

    // =====================================================================
    // Assembly
    // =====================================================================

    private class StationDraft(
        val id: String,
        val name: String,
        val latLng: LatLng,
        val zoneId: String,
        val underground: Boolean,
    )

    private class CityBuilder(private val base: LatLng) {
        private val drafts = LinkedHashMap<String, StationDraft>()
        private val routes = ArrayList<RouteLine>()
        private val edges = ArrayList<TransitEdge>()

        fun station(id: String, name: String, eastM: Double, northM: Double, zoneId: String, underground: Boolean) {
            require(drafts.put(id, StationDraft(id, name, place(base, eastM, northM), zoneId, underground)) == null) {
                "duplicate station id $id"
            }
        }

        /**
         * Registers [line] and emits two directed edges per hop. [hopTimesSec] has one
         * entry per consecutive pair, plus a final entry for the closing hop when
         * [closeLoop] is set (loops have no termini).
         */
        fun route(line: RouteLine, hopTimesSec: List<Int>, closeLoop: Boolean) {
            val ids = line.orderedStationIds
            val hops = ids.zipWithNext().toMutableList()
            if (closeLoop) hops += ids.last() to ids.first()
            require(hopTimesSec.size == hops.size) { "route ${line.id}: ${hops.size} hops, ${hopTimesSec.size} times" }
            routes += line
            for ((index, hop) in hops.withIndex()) {
                val (fromId, toId) = hop
                val d = distance(fromId, toId)
                edges += TransitEdge(fromId, toId, line.id, hopTimesSec[index], d)
                edges += TransitEdge(toId, fromId, line.id, hopTimesSec[index], d)
            }
        }

        /** Walking transfer (routeId = null): two directed edges, time = d / 1.2 m/s + 60 s. */
        fun transfer(aId: String, bId: String) {
            val d = distance(aId, bId)
            require(d <= 250.0) { "transfer $aId-$bId is ${"%.0f".format(d)} m, over the 250 m rule" }
            val time = (d / WALK_SPEED_MPS + TRANSFER_PENALTY_SEC).roundToInt()
            edges += TransitEdge(aId, bId, null, time, d)
            edges += TransitEdge(bId, aId, null, time, d)
        }

        fun build(cityId: String, displayName: String, defaultStartStationId: String): CityFile {
            val routeIdsByStation = HashMap<String, MutableList<String>>()
            for (route in routes) {
                for (id in route.orderedStationIds) {
                    require(id in drafts) { "route ${route.id} references unknown station $id" }
                    routeIdsByStation.getOrPut(id) { ArrayList() } += route.id
                }
            }
            val termini = routes
                .filter { route -> edges.none { it.routeId == route.id && it.fromId == route.orderedStationIds.last() && it.toId == route.orderedStationIds.first() } }
                .flatMap { listOf(it.orderedStationIds.first(), it.orderedStationIds.last()) }
                .toSet()
            val modeByRoute = routes.associate { it.id to it.mode }
            val stations = drafts.values.map { draft ->
                val routeIds = routeIdsByStation[draft.id].orEmpty()
                Station(
                    id = draft.id,
                    name = draft.name,
                    latLng = draft.latLng,
                    // Shared stations take the "heaviest" mode (lowest TransitMode ordinal).
                    mode = routeIds.minOf { modeByRoute.getValue(it).ordinal }.let { TransitMode.entries[it] },
                    routeIds = routeIds,
                    isInterchange = routeIds.size >= 2,
                    isTerminus = draft.id in termini,
                    zoneId = draft.zoneId,
                    underground = draft.underground,
                )
            }
            return CityCodec.fromNetwork(
                network = io.terminus.core.transit.TransitNetwork(stations, routes, edges),
                cityId = cityId,
                displayName = displayName,
                attribution = ATTRIBUTION,
                isSynthetic = true,
                defaultStartStationId = defaultStartStationId,
            )
        }

        private fun distance(aId: String, bId: String): Double {
            val d = GeoMath.haversineMeters(drafts.getValue(aId).latLng, drafts.getValue(bId).latLng)
            return Math.round(d * 10.0) / 10.0 // 0.1 m grid keeps regeneration platform-stable
        }
    }

    /** Meters in one degree of latitude on the sphere used by [GeoMath]. */
    private val METERS_PER_DEG_LAT = StrictMath.toRadians(1.0) * GeoMath.EARTH_RADIUS_METERS

    /** [base] displaced [eastM]/[northM] meters, rounded to 6 decimal places (~0.11 m). */
    private fun place(base: LatLng, eastM: Double, northM: Double): LatLng {
        val lat = base.lat + northM / METERS_PER_DEG_LAT
        val lon = base.lon + eastM / (METERS_PER_DEG_LAT * StrictMath.cos(StrictMath.toRadians(base.lat)))
        return LatLng(round6(lat), round6(lon))
    }

    private fun round6(value: Double): Double = Math.round(value * 1e6) / 1e6
}
